services:

  postgres-db:
    image: postgres:16
    container_name: postgres-db

    restart: always

    environment:
      POSTGRES_DB: policydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass@3808

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - policy-network


  policy-api:

    build:
      context: ./Policy-Management-Service

    container_name: policy-api

    depends_on:
      - postgres-db

    ports:
      - "8080:8080"

    environment:
      SPRING_PROFILES_ACTIVE: docker

    networks:
      - policy-network


  policy-ui:
    build:
      context: ./Policy-Management-ui

    container_name: policy-ui

    depends_on:
      - policy-api

    ports:
      - "80:80"

    networks:
    - policy-network


volumes:

  postgres-data:


networks:

  policy-network: